### ISSUE TITLE
Prepare to merge biscuit branch to master and release rCore v0.2

### ISSUE THREAD

**Issue by wangrunji0408** [oscourse-tsinghua/rcore_plus#20]
## What's new in rCore v0.2?
- Support native Linux musl static programs:
  - Rust std for `x86_64-unknown-linux-musl` target
  - Busybox
  - Biscuit programs on musl
- Support basic file system and socket syscalls
  - [Status](https://github.com/oscourse-tsinghua/rcore_plus/wiki/Biscuit-Syscall-&-Program-Status)

## TODO
- [x] FS: Update `mksfs` to `rcore-fs-fuse`
- [x] User: add Redis and Nginx
- [x] User: pass Travis CI
- [x] Travis CI: make sure compiling pass on all arch
- [x] Travis CI: auto test for some biscuit programs on x86_64
- [x] Net: Intel 82599 driver and improve performance (offload)
- [x] Optimize imports and run `cargo fmt`
- [x] Update README

**Comment by jiegec** [comment]
Dunno how to fix the current bootloader build failure on aarch64.
